{{- if and .Values.postgres.enabled (not .Values.config.dbHost) }}
{{- if .Values.postgres.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres.serviceAccountName" . }}
  labels:
{{- include "postgres.labels" . | nindent 4 }}
  annotations:
{{- .Values.postgres.serviceAccount.annotations | toYaml | nindent 4 }}
{{- end }}
{{- end }}
