{{- if and .Values.postgres.enabled (not .Values.config.dbHost) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
{{- include "postgres.labels" . | nindent 4 }}
{{- if .Values.postgres.service.labels }}
{{- .Values.postgres.service.labels | toYaml | nindent 4 }}
{{- end }}
  annotations:
{{- .Values.postgres.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
{{- if eq .Values.postgres.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.postgres.service.loadBalancerIP }}
  loadBalancerSourceRanges:
{{- .Values.postgres.service.loadBalancerSourceRanges | toYaml | nindent 4 }}
{{- end }}
  externalIPs:
{{- .Values.postgres.service.externalIPs | toYaml | nindent 4 }}
{{- if .Values.postgres.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.postgres.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.postgres.service.sessionAffinity }}
  sessionAffinity: {{ .Values.postgres.service.sessionAffinity }}
{{- end }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      name: {{ .Values.postgres.service.portName }}
      targetPort: postgres
      protocol: TCP
{{- if eq .Values.postgres.service.type "NodePort" }}
      nodePort: {{ .Values.postgres.service.nodePort }}
{{- end }}
  selector:
{{- include "postgres.selectorLabels" . | nindent 4 }}
{{- end }}
