{{- if .Values.config.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
{{- include "connector.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
{{- include "connector.labels" . | nindent 4 }}
spec:
  commonName: infra-connector
  duration: 2160h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "connector.fullname" . }}
  privateKey:
    rotationPolicy: Always
  renewBefore: 36h0m0s
  secretName: {{ include "connector.fullname" . | printf "%s-certificate-authority"  }}
  usages:
    - server auth
    - client auth
{{- end }}
