apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
{{- include "connector.labels" . | nindent 4 }}
data:
  infra.yaml: |
{{- $config := deepCopy .Values.config }}

{{- range $key, $val := $config.addr }}
{{- $_ := printf ":%.f" $val | set $config.addr $key }}
{{- end }}

{{- $_ := set $config.server "accessKey" "/var/run/secrets/infrahq.com/access-key/access-key" }}

{{- range $key, $val := $config }}
{{- if kindIs "invalid" $val }}
{{- else if kindIs "map" $val }}
    {{ $key }}:
{{- $val | toYaml | nindent 6 }}
{{- else if kindIs "slice" $val }}
    {{ $key }}:
{{- $val | toYaml | nindent 6 }}
{{- else if kindIs "string" $val }}
    {{ $key }}: {{ tpl $val $ }}
{{- else }}
    {{ $key }}: {{ $val }}
{{- end }}
{{- end }}
