apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.fullname" . }}-certificate-authority
  labels:
{{- include "connector.labels" . | nindent 4 }}
data:
{{- $secret := include "connector.fullname" . | printf "%s-certificate-authority" | lookup "v1" "Secret" .Release.Namespace }}
{{- if $secret.data }}
  ca.crt: |
{{- get $secret.data "ca.crt" | nindent 4 }}
  ca.key: |
{{- get $secret.data "ca.key" | nindent 4 }}
{{- else }}
{{- $ca := genCA "infra-connector" 3650 }}
  ca.crt: |
{{- $ca.Cert | b64enc | nindent 4 }}
  ca.key: |
{{- $ca.Key | b64enc | nindent 4 }}
{{- end }} {{/* if secret.data */}}
---
{{- if .Values.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.fullname" . }}-access-key
  labels:
{{- include "connector.labels" . | nindent 4 }}
data:
  access-key: {{ .Values.accessKey | b64enc | quote }}
{{- end }} {{/* if .Values.accessKey */}}
