apiVersion: v1
kind: Service
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
{{- include "connector.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{- .Values.service.labels | toYaml | nindent 4 }}
{{- end }}
  annotations:
{{- .Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  loadBalancerSourceRanges:
{{- .Values.service.loadBalancerSourceRanges | toYaml | nindent 4 }}
{{- end }}
  externalIPs:
{{- .Values.service.externalIPs | toYaml | nindent 4 }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
{{- end }}
  ports:
    - port: {{ .Values.service.securePort }}
      name: {{ .Values.service.securePortName }}
      targetPort: https
      protocol: TCP
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.secureNodePort }}
{{- end }}
  selector:
{{- include "connector.selectorLabels" . | nindent 4 }}
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "connector.fullname" . }}-metrics
  labels:
{{- include "connector.labels" . | nindent 4 }}
{{- if .Values.metrics.service.labels }}
{{- .Values.metrics.service.labels | toYaml | nindent 4 }}
{{- end }}
  annotations:
{{- .Values.metrics.service.annotations | toYaml | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.service.port }}
      name: {{ .Values.metrics.service.portName }}
      targetPort: metrics
      protocol: TCP
  selector:
{{- include "connector.selectorLabels" . | nindent 4 }}
{{- end }}
