{{- if .Values.ui.enabled }}
{{- if .Values.ui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ui.serviceAccountName" . }}
  labels:
{{- include "ui.labels" . | nindent 4 }}
  annotations:
{{- toYaml .Values.ui.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
