name: lint-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.list-changed.outputs.charts }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v1
      - uses: actions/setup-python@v2
      - uses: helm/chart-testing-action@v2.2.1
      - id: list-changed
        run: |
          echo "::set-output name=charts::$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} | jq -cnR '[inputs | {name: split("/")[-1], path: .}]')"


  lint:
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        chart: ${{ fromJson(needs.prepare.outputs.charts) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v1
      - uses: actions/setup-python@v2
      - uses: helm/chart-testing-action@v2.2.1
      - run: ct lint --charts ${{ matrix.chart.path }} --validate-maintainers=false

  test:
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        chart: ${{ fromJson(needs.prepare.outputs.charts) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v1
      - uses: actions/setup-python@v2
      - uses: helm/chart-testing-action@v2.2.1
      - uses: helm/kind-action@v1.4.0
        with:
          cluster_name: chart-testing-${{ matrix.chart.name }}
      - run: ct install --charts ${{ matrix.chart.path }}
