name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name "infrahq-ci"
          git config user.email "contact@infrahq.com"
      - uses: azure/setup-helm@v3
      - uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_PAGES_BRANCH: pages
          CR_OWNER: infrahq-ci
          CR_SKIP_EXISTING: 'true'
