{{- if .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "server.serviceAccountName" . }}
  labels:
{{- include "server.labels" . | nindent 4 }}
  annotations:
{{- .Values.server.serviceAccount.annotations | toYaml | nindent 4 }}
{{- end }}
